--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2 (Debian 14.2-1.pgdg110+1)
-- Dumped by pg_dump version 14.1

-- Started on 2022-03-21 11:29:18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 16537)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    number character varying(255) NOT NULL,
    balance numeric(19,2),
    initial_balance numeric(19,2),
    status boolean NOT NULL,
    type character varying(255),
    customer_id bigint NOT NULL
);


ALTER TABLE public.account OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16545)
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    customer_id bigint NOT NULL,
    address character varying(255),
    age integer NOT NULL,
    gender character varying(255),
    identification character varying(255),
    name character varying(255),
    phone character varying(255),
    password character varying(255),
    status boolean
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16544)
-- Name: customer_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 16553)
-- Name: movement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movement (
    id bigint NOT NULL,
    balance numeric(19,2),
    date date,
    movement_type character varying(255),
    value numeric(19,2),
    account_id character varying(255),
    customer_id bigint
);


ALTER TABLE public.movement OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16552)
-- Name: movement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3324 (class 0 OID 16537)
-- Dependencies: 209
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--

--
-- TOC entry 3326 (class 0 OID 16545)
-- Dependencies: 211
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: postgres
--


--
-- TOC entry 3334 (class 0 OID 0)
-- Dependencies: 210
-- Name: customer_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customer_customer_id_seq', 2, true);


--
-- TOC entry 3335 (class 0 OID 0)
-- Dependencies: 212
-- Name: movement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movement_id_seq', 5, true);


--
-- TOC entry 3177 (class 2606 OID 16543)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (number);


--
-- TOC entry 3179 (class 2606 OID 16551)
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (customer_id);


--
-- TOC entry 3181 (class 2606 OID 16559)
-- Name: movement movement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_pkey PRIMARY KEY (id);


--
-- TOC entry 3182 (class 2606 OID 16560)
-- Name: account fknnwpo0lfq4xai1rs6887sx02k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fknnwpo0lfq4xai1rs6887sx02k FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- TOC entry 3183 (class 2606 OID 16565)
-- Name: movement fkoemeananv9w9qnbcoccbl70a0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT fkoemeananv9w9qnbcoccbl70a0 FOREIGN KEY (account_id) REFERENCES public.account(number);


--
-- TOC entry 3184 (class 2606 OID 16570)
-- Name: movement fkq960xkrhlbqf2esa1dd191tsy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT fkq960xkrhlbqf2esa1dd191tsy FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


-- Completed on 2022-03-21 11:29:19

--
-- PostgreSQL database dump complete
--

